### ISSUE TITLE
App crash when we leave from fragment in tablayout

### ISSUE THREAD

**Issue by kansagrakd108** [yuyakaido/CardStackView#157]
E/UncaughtException: java.lang.IllegalStateException: Observer com.yuyakaido.android.cardstackview.CardStackView$1@a43759 was not registered.
        at android.database.Observable.unregisterObserver(Observable.java:69)
        at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:7017)
        at com.yuyakaido.android.cardstackview.CardStackView.onDetachedFromWindow(CardStackView.java:102)
        at android.view.View.dispatchDetachedFromWindow(View.java:17611)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3729)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3715)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5286)
        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5257)
        at android.view.ViewGroup.removeView(ViewGroup.java:5188)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1550)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by yuyakaido** [comment]
@kansagrakd108 
Thank you for your report!
This issue has been fixed in ver. 2.1.2.
