### ISSUE TITLE
java.lang.IllegalStateException: Observer not registered

### ISSUE THREAD

**Issue by woshiieugene** [yuyakaido/CardStackView#167]
I am using build 2.2.0. 
steps to recreate: 
-> open main activity. 
-> clicks button to open another activity which contains the card stack. 
-> clicks on any card stack which opens another activity. 
-> click back button to go back to the card stack activity. 
-> click back again which goes back to main activity
-> crash. 

My logs are as follow: 

java.lang.IllegalStateException: Observer com.yuyakaido.android.cardstackview.internal.CardStackDataObserver@21e9af7 was not registered.
        at android.database.Observable.unregisterObserver(Observable.java:69)
        at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:7017)
        at com.yuyakaido.android.cardstackview.CardStackView.onDetachedFromWindow(CardStackView.java:62)
        at android.view.View.dispatchDetachedFromWindow(View.java:17536)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3683)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3675)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3509)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6407)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:6384)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:458)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:396)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:125)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4671)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1749)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

_Originally posted by @woshiieugene in https://github.com/yuyakaido/CardStackView/issue_comments#issuecomment-448076840_

**Comment by yuyakaido** [comment]
@woshiieugene @applehong5013 
This issue has been fixed in [2.2.1](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.1).
