### ISSUE TITLE
java.lang.NullPointerException Attempt to invoke virtual method 'void com.yuyakaido.android.cardstackview.CardStackLayoutManager.updateProportion(float, float)' on a null object reference

### ISSUE THREAD

**Issue by chanhbc** [yuyakaido/CardStackView#170]
at com.yuyakaido.android.cardstackview.CardStackView.onInterceptTouchEvent(CardStackView.java:72)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java)
        at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
        at android.app.Activity.dispatchTouchEvent(Activity.java)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
        at android.view.View.dispatchPointerEvent(View.java)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
    	at an

This error occurs when the data has not been loaded yet but has been clicked on CardStackView

**Comment by yuyakaido** [comment]
@chanhbc 
This issue has been fixed in [2.2.1](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.1).
