### ISSUE TITLE
fast swipe getTop null pointer

### ISSUE THREAD

**Issue by kolllor33** [yuyakaido/CardStackView#180]
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
                        at com.yuyakaido.android.cardstackview.CardStackLayoutManager.updateProportion(CardStackLayoutManager.java:165)
                        at com.yuyakaido.android.cardstackview.CardStackView.onTouch(CardStackView.java:48)
                        at android.view.View.dispatchTouchEvent(View.java:10713)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2859)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2535)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
                        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2492)
                        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:559)
                        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1870)
                        at android.app.Activity.dispatchTouchEvent(Activity.java:3236)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
                        at android.view.View.dispatchPointerEvent(View.java:10946)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5110)
                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4962)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4645)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4702)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4546)
                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4512)
                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4520)
                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4493)
                        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7000)
                        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6929)
                    	at android.view.ViewRootImpl.enqueueInputEvent(V

Got this nullpointer error when fast swiping.
I already took a look at isseu #51 but nothing in here helped.

**Comment by SaloniPalod** [comment]
i have the same issue

**Comment by kolllor33** [comment]
Have you guys tried update the library to the newest version(2.2.2). I have done this and the error didn't occurred any more for me

**Comment by Aqua-Ye** [comment]
I am using 2.2.2 and have the issue too.

**Comment by andreoromera** [comment]
Same problem here. Doesn't occur often, but it does eventually

**Comment by yuyakaido** [comment]
@kolllor33 @andy85048 @SaloniPalod @Aqua-Ye @andreoromera 
This issue has been fixed in [Ver. 2.2.3](https://github.com/yuyakaido/CardStackView/releases/tag/v2.2.3).

**Comment by Aqua-Ye** [comment]
thank you @yuyakaido

**Comment by richanshah** [comment]
@yuyakaido  still geting issue in latest version , please guide towards this
