### ISSUE TITLE
Attempt to invoke virtual method 'int com.yuyakaido.android.cardstackview.Direction.ordinal()' on a null object reference

### ISSUE THREAD

**Issue by andreoromera** [yuyakaido/CardStackView#193]
Users are reporting this bug. Couldn't reproduce it, but happend twice.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yuyakaido.android.cardstackview.Direction.ordinal()' on a null object reference
       at com.yuyakaido.android.cardstackview.internal.CardStackSmoothScroller.getDx(CardStackSmoothScroller.java:135)
       at com.yuyakaido.android.cardstackview.internal.CardStackSmoothScroller.onTargetFound(CardStackSmoothScroller.java:52)
       at androidx.recyclerview.widget.RecyclerView$SmoothScroller.onAnimation(RecyclerView.java:11758)
       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5243)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
       at android.view.Choreographer.doFrame(Choreographer.java:603)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by yuyakaido** [comment]
@andreoromera 
I also can't reproduce this issue. Do you pass null as a direction when build an instance of `SwipeAnimationSetting` or `RewindAnimationSetting`? These settings doesn't accept null as a direction.

**Comment by andreoromera** [comment]
> @andreoromera
> I also can't reproduce this issue. Do you pass null as a direction when building an instance of `SwipeAnimationSetting` or `RewindAnimationSetting`? These settings doesn't accept null as a direction.

@yuyakaido 
There is a case where I am MAYBE passing null as you pointed out. I will look into it. Thank you!
