### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter view app.blackgentry.ui.homeScreen.fragment.FindMatchFragment.onCardDisappeared

### ISSUE THREAD

**Issue by osvinphp** [yuyakaido/CardStackView#323]
Fatal Exception: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter view
       at app.blackgentry.ui.homeScreen.fragment.FindMatchFragment.onCardDisappeared(:3)
       at com.yuyakaido.android.cardstackview.internal.CardStackSmoothScroller.onStart(CardStackSmoothScroller.java:108)
       at androidx.recyclerview.widget.RecyclerView$SmoothScroller.start(RecyclerView.java:11813)
       at androidx.recyclerview.widget.RecyclerView$LayoutManager.startSmoothScroll(RecyclerView.java:8470)
       at com.yuyakaido.android.cardstackview.CardStackLayoutManager.smoothScrollToNext(CardStackLayoutManager.java:544)
       at com.yuyakaido.android.cardstackview.CardStackLayoutManager.onScrollStateChanged(CardStackLayoutManager.java:183)
       at androidx.recyclerview.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:5197)
       at androidx.recyclerview.widget.RecyclerView.setScrollState(RecyclerView.java:1550)
       at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5397)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:986)
       at android.view.Choreographer.doCallbacks(Choreographer.java:764)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by richanshah** [comment]
find any solutuon ? @osvinphp
