### ISSUE TITLE
 java.lang.IllegalArgumentException Cannot set 'scaleX' to Float.NaN

### ISSUE THREAD

**Issue by chim0380** [yuyakaido/CardStackView#370]
Sometimes exceptions exist:
Fatal Exception: java.lang.IllegalArgumentException
**Cannot set 'scaleX' to Float.NaN**

Latest version of library

Last device: TECNO SPARK Go 2022 on Android 11

Orientation: Landscape

Stack Trace:
android.view.View.sanitizeFloatPropertyValue (View.java:17545)
android.view.View.sanitizeFloatPropertyValue (View.java:17519)
android.view.View.setScaleX (View.java:16888)
com.yuyakaido.android.cardstackview.CardStackLayoutManager.updateScale (CardStackLayoutManager.java:417)
com.yuyakaido.android.cardstackview.CardStackLayoutManager.update (CardStackLayoutManager.java:348)
com.yuyakaido.android.cardstackview.CardStackLayoutManager.onLayoutChildren (CardStackLayoutManager.java:51)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:4309)
androidx.recyclerview.widget.RecyclerView.dispatchLayout (RecyclerView.java:4012)
androidx.recyclerview.widget.RecyclerView.onLayout (RecyclerView.java:4578)
CardStackViewEdge.onLayout (CardStackViewEdge.java:40)

**Comment by KamiNoYuki** [comment]
Me too：
`java.lang.IllegalArgumentException: Cannot set 'scaleX' to Float.NaN
at android.view.View.sanitizeFloatPropertyValue(View.java:18259)
at android.view.View.sanitizeFloatPropertyValue(View.java:18233)
at android.view.View.setScaleX(View.java:17598)
at com.yuyakaido.android.cardstackview.CardStackLayoutManager.updateScale(CardStackLayoutManager.java:417)
at com.yuyakaido.android.cardstackview.CardStackLayoutManager.update(CardStackLayoutManager.java:348)
at com.yuyakaido.android.cardstackview.CardStackLayoutManager.onLayoutChildren(CardStackLayoutManager.java:51)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4307)
at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4873)
at android.view.View.layout(View.java:23798)
at android.view.ViewGroup.layout(ViewGroup.java:6413)`
How to fixed it.

**Comment by Ayusch** [comment]
Same here,

I'm trying to use this with Compose.
