### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dsuresh-ap** [yuyakaido/CardStackView#40]
Got this crash using beta8. Not sure how to reproduce it but I will post re-produce steps when I can.

11-06 12:13:14.512 11196-11196/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference
                                                       at com.yuyakaido.android.cardstackview.internal.CardContainerView.onTouchEvent(CardContainerView.java:91)
                                                       at android.view.View.dispatchTouchEvent(View.java:10025)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2663)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:963)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2669)
                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
                                                       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:413)
                                                       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:3061)
                                                       at com.promgirl.speedshop.activities.SpeedShopActivity.dispatchTouchEvent(SpeedShopActivity.java:609)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:375)
                                                       at android.view.View.dispatchPointerEvent(View.java:10245)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4433)
                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4301)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3848)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3901)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3867)
                                                       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3994)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3875)
                                                       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4051)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3848)
                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3901)
                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3867)
                                                       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3875)
                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3848)
                                                       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6209)
11-06 12:13:14.512 11196-11196/? E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6183)
                                                       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6144)
                                                       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6312)
                                                       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                       at android.os.MessageQueue.nativePollOnce(Native Method)
                                                       at android.os.MessageQueue.next(MessageQueue.java:323)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6088)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by dsuresh-ap** [comment]
I believe this happens when swiping fast

**Comment by subhamkotiyal** [comment]
Get the same issue , Any solution ??

**Comment by felixwcf** [comment]
I'm facing this issue too when swiping the cards very fast. I had a deadline to catch, so this is a temporary solution: https://stackoverflow.com/questions/22978245/how-to-prevent-android-app-from-crashing-due-to-exception-in-background-thread.

**Comment by vmichalak** [comment]
I have the same issue !

**Comment by vmichalak** [comment]
Problem disapear when visible count is at 1

**Comment by wzieba** [comment]
+1, same here

**Comment by yuyakaido** [comment]
@dsuresh-ap @subhamkotiyal @felixwcf @vmichalak @wzieba 
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
