### ISSUE TITLE
Fast swiping procduces null pointer

### ISSUE THREAD

**Issue by Arazjel** [yuyakaido/CardStackView#51]
NullPointer logcat on fast swiping 

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.ViewParent android.view.ViewParent.getParent()' on a null object reference
                                                                                  at com.yuyakaido.android.cardstackview.internal.CardContainerView.onTouchEvent(CardContainerView.java:91)
                                                                                  at android.view.View.dispatchTouchEvent(View.java:10110)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2776)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2408)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2810)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
                                                                                  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2422)
                                                                                  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
                                                                                  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
                                                                                  at android.app.Activity.dispatchTouchEvent(Activity.java:3072)
                                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                  at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
                                                                                  at android.view.View.dispatchPointerEvent(View.java:10341)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
                                                                                  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
                                                                                  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                                  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
                                                                                  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
                                                                                  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
                                                                                  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
                                                                                  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
                                                                                  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
                                                                                  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
                                                                                  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
                                                                                  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                  at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                  at android.os.MessageQueue.next(MessageQueue.java:328)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6361)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                              	at com.android.internal.
```

**Comment by artemkutukov** [comment]
+1

**Comment by KavithaAnandan** [comment]
Add handler to solve this issue. It works well. Happy coding.
   new Handler().postDelayed(new Runnable() {
 if (cardStackView.getTopIndex() == adapter.getCount() - 5) {
                    Log.d("CardStackView", "Paginate: " + cardStackView.getTopIndex());
                    paginate();
                }
 }, 500);

**Comment by vmichalak** [comment]
what is your paginate method ?

**Comment by yuyakaido** [comment]
@Arazjel @kutukoff @KavithaAnandan @vmichalak 
This issue has been fixed in [ver. 2.0.0](https://github.com/yuyakaido/CardStackView/pull/137).
